### PR TITLE
fix vcrpy version requirement for testing, reduce verbosity of test log

### LINKED ISSUE #735: vcrpy 1.13
We've python-vcrpy 1.13 in Fedora 29 and have python3-vcrpy as an enforced build dependency. 
Try to start tests fail with an error:
```
+ cd pyvmomi-6.7.1
+ /usr/bin/python3 setup.py test
running test
Searching for vcrpy==1.12.0
Reading https://pypi.org/simple/vcrpy/
Download error on https://pypi.org/simple/vcrpy/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't retrieve index page for 'vcrpy'
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for vcrpy==1.12.0
error: Could not find suitable distribution for Requirement.parse('vcrpy==1.12.0')
```

### PR DESCRIPTION
**Pull request by jeking3**
This fixes #735 

```
jking@dvm:~/pyvmomi$ tox
GLOB sdist-make: /home/jking/pyvmomi/setup.py
py27 create: /home/jking/pyvmomi/.tox/py27
py27 installdeps: -rtest-requirements.txt
py27 inst: /home/jking/pyvmomi/.tox/dist/pyvmomi-6.7.1.zip
py27 installed: certifi==2018.10.15,chardet==3.0.4,contextlib2==0.5.5,extras==1.0.0,filelock==3.0.10,fixtures==3.0.0,funcsigs==1.0.2,idna==2.7,linecache2==1.0.0,mock==2.0.0,pbr==5.1.0,pkg-resources==0.0.0,pluggy==0.8.0,py==1.7.0,python-mimeparse==1.6.0,pyvmomi==6.7.1,PyYAML==3.13,requests==2.20.0,six==1.11.0,testtools==2.3.0,toml==0.10.0,tox==3.5.3,traceback2==1.4.0,unittest2==1.1.0,urllib3==1.24.1,vcrpy==1.13.0,virtualenv==16.1.0,wrapt==1.10.11
py27 runtests: PYTHONHASHSEED='1076960615'
py27 runtests: commands[0] | python setup.py test
running test
running egg_info
writing dependency_links to pyvmomi.egg-info/dependency_links.txt
writing pyvmomi.egg-info/PKG-INFO
writing top-level names to pyvmomi.egg-info/top_level.txt
writing requirements to pyvmomi.egg-info/requires.txt
reading manifest file 'pyvmomi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyvmomi.egg-info/SOURCES.txt'
running build_ext
test_basic_container_view (tests.test_container_view.ContainerViewTests) ... ok
test_root_folder_parent (tests.test_managed_object.ManagedObjectTests) ... ok
test_iso8601_set_datetime (tests.test_iso8601.Iso8601Tests) ... ok
test_vm_config_iso8601 (tests.test_iso8601.Iso8601Tests) ... ok
test_request_context_serializer_global (tests.test_serializer.SerializerTests) ... ok
test_request_context_serializer_instance (tests.test_serializer.SerializerTests) ... ok
test_serialize_float (tests.test_serializer.SerializerTests) ... ok
test_serialize_integer (tests.test_serializer.SerializerTests) ... ok
test_serialize_object (tests.test_serializer.SerializerTests) ... ok
test_serialize_unicode (tests.test_serializer.SerializerTests) ... ok
test_simple_request_serializer (tests.test_serializer.SerializerTests) ... ok
test_basic_connection (tests.test_connect.ConnectionTests) ... ok
test_basic_connection_bad_password (tests.test_connect.ConnectionTests) ... ok
test_disconnect_on_no_connection (tests.test_connect.ConnectionTests) ... ok
test_smart_connection (tests.test_connect.ConnectionTests) ... ok
test_ssl_tunnel (tests.test_connect.ConnectionTests) ... ok
test_ssl_tunnel_http_failure (tests.test_connect.ConnectionTests) ... ok
test_sspi_connection (tests.test_connect.ConnectionTests) ... ok
test_vm_nic_data (tests.test_virtual_machine_object.VirtualMachineTests) ... ok
test_invoke_method_login_session_exception (tests.test_vim_session_oriented_stub.SoapAdapterTests) ... ok
test_json_datacenter_explode (tests.test_json.JSONTests) ... ok
test_json_datastore_explode (tests.test_json.JSONTests) ... ok
test_json_host_explode (tests.test_json.JSONTests) ... ok
test_json_network_explode (tests.test_json.JSONTests) ... ok
test_json_vm_explode_default (tests.test_json.JSONTests) ... ok
test_json_vm_explode_objs_match (tests.test_json.JSONTests) ... ok
test_json_vm_explode_type_match (tests.test_json.JSONTests) ... ok
test_pbm_check_compatibility (tests.test_pbm_check_compatibility.PBMTests) ... ok

----------------------------------------------------------------------
Ran 28 tests in 7.912s

OK
py36 create: /home/jking/pyvmomi/.tox/py36
py36 installdeps: -rtest-requirements.txt
py36 inst: /home/jking/pyvmomi/.tox/dist/pyvmomi-6.7.1.zip
py36 installed: certifi==2018.10.15,chardet==3.0.4,extras==1.0.0,filelock==3.0.10,fixtures==3.0.0,idna==2.7,linecache2==1.0.0,multidict==4.4.2,pbr==5.1.0,pkg-resources==0.0.0,pluggy==0.8.0,py==1.7.0,python-mimeparse==1.6.0,pyvmomi==6.7.1,PyYAML==3.13,requests==2.20.0,six==1.11.0,testtools==2.3.0,toml==0.10.0,tox==3.5.3,traceback2==1.4.0,unittest2==1.1.0,urllib3==1.24.1,vcrpy==1.13.0,virtualenv==16.1.0,wrapt==1.10.11,yarl==1.2.6
py36 runtests: PYTHONHASHSEED='1076960615'
py36 runtests: commands[0] | python setup.py test
running test
running egg_info
writing pyvmomi.egg-info/PKG-INFO
writing dependency_links to pyvmomi.egg-info/dependency_links.txt
writing requirements to pyvmomi.egg-info/requires.txt
writing top-level names to pyvmomi.egg-info/top_level.txt
reading manifest file 'pyvmomi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyvmomi.egg-info/SOURCES.txt'
running build_ext
test_basic_container_view (tests.test_container_view.ContainerViewTests) ... ok
test_root_folder_parent (tests.test_managed_object.ManagedObjectTests) ... ok
test_iso8601_set_datetime (tests.test_iso8601.Iso8601Tests) ... ok
test_vm_config_iso8601 (tests.test_iso8601.Iso8601Tests) ... ok
test_request_context_serializer_global (tests.test_serializer.SerializerTests) ... ok
test_request_context_serializer_instance (tests.test_serializer.SerializerTests) ... ok
test_serialize_float (tests.test_serializer.SerializerTests) ... ok
test_serialize_integer (tests.test_serializer.SerializerTests) ... ok
test_serialize_object (tests.test_serializer.SerializerTests) ... ok
test_serialize_unicode (tests.test_serializer.SerializerTests) ... ok
test_simple_request_serializer (tests.test_serializer.SerializerTests) ... ok
test_basic_connection (tests.test_connect.ConnectionTests) ... ok
test_basic_connection_bad_password (tests.test_connect.ConnectionTests) ... ok
test_disconnect_on_no_connection (tests.test_connect.ConnectionTests) ... ok
test_smart_connection (tests.test_connect.ConnectionTests) ... ok
test_ssl_tunnel (tests.test_connect.ConnectionTests) ... /home/jking/pyvmomi/tests/test_connect.py:90: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  connect.SoapStubAdapter('sdkTunnel', 8089, httpProxyHost='vcsa').GetConnection()
ok
test_ssl_tunnel_http_failure (tests.test_connect.ConnectionTests) ... ok
test_sspi_connection (tests.test_connect.ConnectionTests) ... ok
test_vm_nic_data (tests.test_virtual_machine_object.VirtualMachineTests) ... ok
test_invoke_method_login_session_exception (tests.test_vim_session_oriented_stub.SoapAdapterTests) ... ok
test_json_datacenter_explode (tests.test_json.JSONTests) ... ok
test_json_datastore_explode (tests.test_json.JSONTests) ... ok
test_json_host_explode (tests.test_json.JSONTests) ... ok
test_json_network_explode (tests.test_json.JSONTests) ... ok
test_json_vm_explode_default (tests.test_json.JSONTests) ... ok
test_json_vm_explode_objs_match (tests.test_json.JSONTests) ... ok
test_json_vm_explode_type_match (tests.test_json.JSONTests) ... ok
test_pbm_check_compatibility (tests.test_pbm_check_compatibility.PBMTests) ... ok

----------------------------------------------------------------------
Ran 28 tests in 7.536s

OK
__________________________________________________________________________________________ summary ___________________________________________________________________________________________
  py27: commands succeeded
  py36: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by sathieu** [comment]
You can replace `vcrpy<2` by simply `vcrpy`.  The only breaking change in 2.0.0 and 2.0.1 is `Drop support to python 3.4 asyncio.coroutine` with 2.0.1 having `Fix bug when using vcrpy with python 3.4` (see [changelog](https://github.com/kevin1024/vcrpy/blob/master/docs/changelog.rst))

**Comment by jeking3** [comment]
These builds failed when I just had `vcrpy` as a dependency about 2 weeks ago.

**Comment by sathieu** [comment]
@jeking3 I have this error with packages from Debian sid (vcrpy=2.0.1):
```
======================================================================
ERROR: test_ssl_tunnel (tests.test_connect.ConnectionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 151, in _handle_function
    return fn(cassette)
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/build/python-pyvmomi-6.7.1/tests/test_connect.py", line 90, in test_ssl_tunnel
    connect.SoapStubAdapter('sdkTunnel', 8089, httpProxyHost='vcsa').GetConnection()
  File "/build/python-pyvmomi-6.7.1/pyVmomi/SoapAdapter.py", line 1405, in GetConnection
    result = self.scheme(self.host, **self.schemeArgs)
  File "/build/python-pyvmomi-6.7.1/pyVmomi/SoapAdapter.py", line 1088, in __call__
    resp = tunnel.getresponse()
  File "/usr/lib/python3/dist-packages/vcr/stubs/__init__.py", line 220, in getresponse
    if self.cassette.can_play_response_for(self._vcr_request):
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 258, in can_play_response_for
    return request and request in self and \
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 329, in __contains__
    for index, response in self._responses(request):
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 253, in _responses
    if requests_match(request, stored_request, self._match_on):
  File "/usr/lib/python3/dist-packages/vcr/matchers.py", line 99, in requests_match
    matches = [(m(r1, r2), m) for m in matchers]
  File "/usr/lib/python3/dist-packages/vcr/matchers.py", line 99, in <listcomp>
    matches = [(m(r1, r2), m) for m in matchers]
  File "/usr/lib/python3/dist-packages/vcr/matchers.py", line 27, in port
    return r1.port == r2.port
  File "/usr/lib/python3/dist-packages/vcr/request.py", line 61, in port
    port = {'https': 443, 'http': 80}[parse_uri.scheme]
KeyError: ''

======================================================================
ERROR: test_ssl_tunnel_http_failure (tests.test_connect.ConnectionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 151, in _handle_function
    return fn(cassette)
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/build/python-pyvmomi-6.7.1/tests/test_connect.py", line 99, in test_ssl_tunnel_http_failure
    self.assertRaises(http_client.HTTPException, should_fail)
  File "/usr/lib/python3.7/unittest/case.py", line 743, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.7/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "/build/python-pyvmomi-6.7.1/tests/test_connect.py", line 98, in should_fail
    connect.SoapStubAdapter('vcsa', 80, httpProxyHost='vcsa').GetConnection()
  File "/build/python-pyvmomi-6.7.1/pyVmomi/SoapAdapter.py", line 1405, in GetConnection
    result = self.scheme(self.host, **self.schemeArgs)
  File "/build/python-pyvmomi-6.7.1/pyVmomi/SoapAdapter.py", line 1088, in __call__
    resp = tunnel.getresponse()
  File "/usr/lib/python3/dist-packages/vcr/stubs/__init__.py", line 220, in getresponse
    if self.cassette.can_play_response_for(self._vcr_request):
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 258, in can_play_response_for
    return request and request in self and \
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 329, in __contains__
    for index, response in self._responses(request):
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 253, in _responses
    if requests_match(request, stored_request, self._match_on):
  File "/usr/lib/python3/dist-packages/vcr/matchers.py", line 99, in requests_match
    matches = [(m(r1, r2), m) for m in matchers]
  File "/usr/lib/python3/dist-packages/vcr/matchers.py", line 99, in <listcomp>
    matches = [(m(r1, r2), m) for m in matchers]
  File "/usr/lib/python3/dist-packages/vcr/matchers.py", line 27, in port
    return r1.port == r2.port
  File "/usr/lib/python3/dist-packages/vcr/request.py", line 61, in port
    port = {'https': 443, 'http': 80}[parse_uri.scheme]
KeyError: ''

----------------------------------------------------------------------
Ran 21 tests in 5.732s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=21 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=21 errors=2 failures=0>
```

**Comment by jeking3** [comment]
Yes, the two ssl tests fail with `vcrpy>=2.0.0`, this is why I set it to `vcrpy<2` to fix the issue.  Originally vmware set it to specifically `vcrpy=1.12.0` however I found `1.13.0` also worked.  That's how I ended up at the pull request solution.

**Comment by sathieu** [comment]
The guilty PR seems to be https://github.com/kevin1024/vcrpy/pull/389.

**Comment by sathieu** [comment]
As a workaround, in Debian sid, I've disabled the two ssl_connect tests. See [debian/patches/0001-Unpin-vcrpy-out-of-1.12.0.patch](https://salsa.debian.org/python-team/modules/python-pyvmomi/blob/910cdbd15c9ded4ebc542c28b0ab2cd15a78e9ac/debian/patches/0001-Unpin-vcrpy-out-of-1.12.0.patch).

**Comment by jeking3** [comment]
@pgbidkar this PR as it is fixes the problem in this repo, and should be merged.  In order to unblock the upstream packagers, we need to figure out why vcrpy >= 2.0 does not work.

**Comment by pgbidkar** [comment]
@jeking3 Merging Changes. Thanks for Contributing 

Thanks

**Pull request merged**
