### PR TITLE
Propose fix typos

### PR DESCRIPTION
**Pull request by jeis2497052**
Are some spelling corrections OK?

### CODE REVIEW

**Comment by jeis2497052** [comment]
Thanks for reviewing.  I can fix that.

**Comment by jeking3** [comment]
I thought the class documentation in this project was deprecated?

**Comment by jeking3** [comment]
@pgbidkar isn't the class documentation deprecated and scheduled to be removed?  If so, this is inconsequential.

**Comment by jeking3** [comment]
@tianhao64 isn't the class documentation deprecated and scheduled to be removed? If so, this is inconsequential.

**Comment by jeking3** [comment]
@pgbidkar @tianhao64 this issue can be closed, as it is no longer valid.

**Comment by DanielDraganov** [comment]
As explained above this request is no longer relevant.
Changes not concerning the documentation are already introduced in the major update for 8.0: https://github.com/vmware/pyvmomi/commit/a90023fedfeda48cb1824200dc4530084215f99e

**Pull request closed without merging**
