### PR TITLE
Fixing semantic error in Version.py. == vs is

### PR DESCRIPTION
**Pull request by slw07g**

### CODE REVIEW

**Comment by jgknight** [comment]
Any guesses or updates on when this may be accepted?

**Comment by jrett2** [comment]
+1

**Comment by slw07g** [comment]
@hartsock (friendly ping)

**Comment by hartsock** [comment]
@slw07g the current VMware technical lead is supposed to be @StefanHristov-VMware now if I'm not mistaken. @StefanHristov-VMware , I don't want to step on your area of technical leadership here. What's going on with community contributions these days?

**Comment by StefanHristov-VMware** [comment]
This area of pyVmomi is severely modified, with this particular issue already fixed. We are planning to release our latest bits sometime during the next month.

**Pull request merged**
