### PR TITLE
Adding support for using VICredStore credentials files to provide use…

### PR DESCRIPTION
**Pull request by borland667**
Hello, I have added support to use existing vicredentials.xml files in my fork. Hopefully you will include this functionality in the standard release.

### CODE REVIEW

**Comment by borland667** [comment]
Please ignore this one. I just realized I didn't merge with upstream before. 
I will merge everything and put another separate request.

**Comment by michaelrice** [comment]
Hi @borland667 

I see several issues with this p/r. First off Im not sure if you have seen this document but you should consider reading it: https://github.com/vmware/pyvmomi/wiki/Contributions if you have not done so already.

1. There are a lot of commits. You should rebase them out to 1 meaningful commit.
2. Per the document above I think this is a better fit in pyvmomi-tools, not in the core library.
3. Your modifications to the gitignore file should be undone. 
4. Be sure to remove your .idea folder from your commit when you do the rebasing
5. Please include test coverage for new functionality
6. Your changes to the sample file look to all be pep8. See the above document about pep8 changes.

If you need any help getting any of these things done please feel free to pop into IRC and someone should be able to help you out. My nick in there is ```errr```

Thanks!

**Comment by borland667** [comment]
Cheers Mike. Sorry I didn't see any of the mentioned docs.

Will check them out and do it properly.

**Comment by borland667** [comment]
I will move this to pyvmomi-tools as per recommendations and include unit tests.

**Pull request closed without merging**
